### ISSUE TITLE
chiselName on abstract classes with unimplemented methods chokes compilation

### ISSUE THREAD

**Issue by kammoh** [chipsalliance/chisel3#1132]
**Type of issue**: bug report

**Impact**: unknown

**Development Phase**: request

**Other information**
```
Error:(6, 2) no type parameters for method popReturnContext: (prefixRef: T, until: chisel3.internal.naming.NamingContextInterface)T exist so that it can be applied to arguments (<notype>, chisel3.internal.naming.NamingContextInterface)
 --- because ---
argument expression's type is not compatible with formal parameter type;
 found   : <notype>
 required: ?T
Note that <none> extends Any, not AnyRef.
Such types can participate in value classes, but instances
cannot appear in singleton types or in reference comparisons.
@chiselName
```
**If the current behavior is a bug, please provide the steps to reproduce the problem:**
```scala
@chiselName
abstract class MyClass {
  def myMethod(x: UInt): UInt
}
```
**What is the current behavior?**
Scala compilation fails.

**What is the expected behavior?**
`chiselName` should just skip unimplemented methods

**Please tell us about your environment:**
    - version: `3.2-SNAPSHOT`
    - OS: `macOS Mojave`

**What is the use case for changing the behavior?**
User's code might contain abstract classes with some hardware nodes that deserve proper naming as well as methods that will be implemented by derived classes.

**Comment by jackkoenig** [comment]
Fixed by introduction of naming plugin in Chisel 3.4
