### ISSUE TITLE
DontCare is hidden from the scaladoc

### ISSUE THREAD

**Issue by johnsbrew** [chipsalliance/chisel3#1727]
**Type of issue**: documentation 

**Impact**: no functional change

**Development Phase**: request

**Other information**
`DontCare` is exposed as a val in package.scala, without any scaladoc
https://github.com/chipsalliance/chisel3/blob/b578aa5e45e4ac5c2a71dda42367863a577ccaa4/core/src/main/scala/chisel3/package.scala#L211

Is there (still?) a good reason to keep the `InternalDontCare` both in package internal & private ?

Workaround to provide some scala doc (a bit ugly though ...):
```scala
/** some useful doc **/
def DontCare = chisel3.internal.InternalDontCare // scalastyle:ignore
```

**If the current behavior is a bug, please provide the steps to reproduce the problem:**
https://www.chisel-lang.org/api/latest/?search=DontCare

**What is the current behavior?**
No scaladoc for DontCare (not even found)

**What is the expected behavior?**
Some doc for DontCare (and found)

**What is the use case for changing the behavior?** 
Better outreach ;-)

**Comment by jackkoenig** [comment]
Yeah this is a bit annoying. It turns out that we probably have to fix this in order to add Scala 2.13 support anyway for Chisel 3.5. I'll see about pull that change out separately so it can be backported to 3.4 though.
