### ISSUE TITLE
how declare dff without reset ?? 

### ISSUE THREAD

**Issue by CaseyZhu** [chipsalliance/chisel3#1734]
**Type of issue**: bug report | feature request | documentation | other enhancement

**Impact**: no functional change | API addition (no impact on existing code) | API modification | unknown

**Development Phase**: request | proposal

**Other information**
 

**If the current behavior is a bug, please provide the steps to reproduce the problem:**

**What is the current behavior?**

**What is the expected behavior?**

**Please tell us about your environment:**

**What is the use case for changing the behavior?**

**Comment by CaseyZhu** [comment]
Type of issue: feature request

**Comment by sequencer** [comment]
https://scastie.scala-lang.org/t0tsPfXGSFmJAmiOYc1kkA

**Comment by schoeberl** [comment]
Why not just:

RegNext(input)
