### ISSUE TITLE
Disagreement between UInt.%, SInt.%, and SInt./ and corresponding Firrtl operations

### ISSUE THREAD

**Issue by aswaterman** [chipsalliance/chisel3#1746]
Firrtl says that `%` should assume the narrower of its operands' widths, whereas `/` on SInt should increase the numerator's width by 1 bit.  Chisel uses the numerator's width in all cases.  If I'm reading the code right, `getWidth` on these results returns a value that disagrees with Firrtl.

Am I reading this right?  If so, it seems like an outright bug, and perhaps changing the Chisel semantics to match Firrtl is a justifiable solution.

**Comment by albert-magyar** [comment]
```
class DivStuff extends MultiIOModule {
  val a = IO(Input(SInt(5.W)))
  val b = IO(Input(SInt(4.W)))
  val o = IO(Output(SInt()))
  val x = a % b
  o := x
  println(x.getWidth)
}
```

Chisel does in fact report of width of 5 for the intermediate, and similarly reports the numerator's width for all the cases you mentioned, while FIRRTL uses the intrinsic width of 4 for the node to infer a width of 4 for the output, so this is a bug.
