### ISSUE TITLE
formatting issue in the "Experimental Features" part of the docs/website

### ISSUE THREAD

**Issue by mwachs5** [chipsalliance/chisel3#1829]
**Type of issue**: documentation

**Impact**: no functional change

**Development Phase**: request

**Other information**
 

**If the current behavior is a bug, please provide the steps to reproduce the problem:**

Go to https://www.chisel-lang.org/chisel3/docs/appendix/experimental-features.html

or 

https://github.com/chipsalliance/chisel3/blob/master/docs/src/appendix/experimental-features.md

**What is the current behavior?**

It looks like this:

<img width="925" alt="Screen Shot 2021-03-22 at 12 55 36 PM" src="https://user-images.githubusercontent.com/17858596/112050374-0420e600-8b0e-11eb-8a10-8f3c4a4fb4c8.png">

**What is the expected behavior?**

There should be a bulleted list of links not all one line

**Please tell us about your environment:**

Chrome

**What is the use case for changing the behavior?**

Make it easier to navigate the docs/website

**Comment by klmrdn** [comment]
I tried to fix it and made a pull request #1844

**Comment by jackkoenig** [comment]
This is fixed.
