### ISSUE TITLE
chisel3.Bool cannot be cast to java.lang.Boolean

### ISSUE THREAD

**Issue by Talha-Ahmed-1** [chipsalliance/chisel3#1837]
I am trying to use chisel3.Bool in **if else** statements but there is an error, expression of **if** should contain java.lang.Boolean. Please guide me how to cast chisel3.Bool into java.lang.Boolean

**Comment by edwardcwang** [comment]
Thank you for your interest in Chisel! Have you worked through the exercises in https://github.com/freechipsproject/chisel-bootcamp ? `Bool` is a hardware type whereas `Boolean` is a software (generation time) type. If you are trying to create a hardware mux, you can use `Mux(myBool, ifHigh, ifLow)`.
