### ISSUE TITLE
Make Gitter chat room publicly accessible

### ISSUE THREAD

**Issue by itviewer** [chipsalliance/chisel3#1847]
Perhaps due to private reasons, new users must log in to access the chat room (public chat rooms do not need to log in to view the history).
The trouble is that it requires permission to access the user's private github repository.
![20210401151538](https://user-images.githubusercontent.com/1397840/113257894-d1d96a80-92fd-11eb-9b08-7681f6603579.png)
Must agree to access the private github  repository
![20210401151559](https://user-images.githubusercontent.com/1397840/113257908-d56cf180-92fd-11eb-98f4-25cd0f517683.png)

**Comment by itviewer** [comment]
It seems that only invited users can join. Isn't this a channel for discussing publicly?

**Comment by itviewer** [comment]
My goodness! see https://github.com/chipsalliance/chisel3/pull/1848

**Comment by seldridge** [comment]
Ack. I don't think I realized that gitter wasn't handling the name change. Sorry about the confusion.
