### ISSUE TITLE
Add `isOneOf` method to `ChiselEnum`

### ISSUE THREAD

**Issue by ekiwi** [chipsalliance/chisel3#1909]
I have been experimenting with replacing the old `Enum`s with the new `ChiselEnum` in `rocket-chip`. One important function that is used a lot, but missing from `ChiselEnum` is `isOneOf`. This should be fairly straight forward  to implement in a type-safe manner.

**Comment by ekiwi** [comment]
This code may be a good starting point if anyone is interested in picking up this issue:

```.scala
  final def isOneOf(s: Seq[EnumType])(implicit sourceInfo: SourceInfo, compileOptions: CompileOptions): Bool = {
    VecInit(s.map(this === _)).asUInt().orR()
  }

  final def isOneOf(u1: EnumType, u2: EnumType*)(implicit sourceInfo: SourceInfo, compileOptions: CompileOptions): Bool
   = isOneOf(u1 +: u2.toSeq)
```

**Comment by ekiwi** [comment]
Once the `isOneOf` method gets added it isn't too hard to change all uses of the legacy `Enum` to use `ChiselEnum` instead:
https://github.com/ekiwi/rocket-chip/commit/1b7263ef323ce0fd289d9cada3cb7eed7114be5d

**Comment by chiplet** [comment]
@ekiwi I'm interested in contributing to chisel and have used `ChiselEnum` quite extensively so this looks like a good first issue for me 😄

**Comment by chiplet** [comment]
I'll begin working on this under PR #1966.

**Comment by schoeberl** [comment]
Slightly OT: could we move (copy) ChiselEnum from experimental either to chisel3 or cisel3.util? Stuff in experimental sounds a bit scary and if it lives too long in experimental, it might be hard to move it out later.

**Comment by ekiwi** [comment]
> Slightly OT: could we move (copy) ChiselEnum from experimental either to chisel3 or cisel3.util? Stuff in experimental sounds a bit scary and if it lives too long in experimental, it might be hard to move it out later.

I wish we had a good process for this. Essentially, what we should do before moving it out of experimental is to have multiple people look at it and see if there is any functionality that should be cut (because it turned out not to be useful) before we give up our right to make breaking changes.
