### ISSUE TITLE
remove parenthesis from `asBool`, `asUInt` methods

### ISSUE THREAD

**Issue by ekiwi** [chipsalliance/chisel3#2088]
A lot of chisel code does not use parenthesis with these methods, but since they are declared with parenthesis, this leads to a bunch of warnings. We should consider following the common usage patterns.

**Comment by mwachs5** [comment]
I believe @jared-barocsi is working on this?

**Comment by ekiwi** [comment]
Yup. This will be fixed with: https://github.com/chipsalliance/chisel3/pull/2124
