### ISSUE TITLE
Chisel Docker's UNIX password

### ISSUE THREAD

**Issue by chaoranli20** [chipsalliance/chisel3#2137]
We are trying to use chisel3-tools docker in dockerhub. However we can't get to root of chisel docker or change the root password when we run the docker in bash.
So what is the root password of Chisel Docker?

Best wishes.

**Comment by edwardcwang** [comment]
I believe you can just run a command as root using Docker no? Once you are root in the container, it should be easy to change the container's root password.

http://gaurav.koley.in/2018/root-user-in-docker-container
