### ISSUE TITLE
Minor doc typos

### ISSUE THREAD

**Issue by Fleker** [chipsalliance/chisel3#2138]
Here's an issue with a few typos I found while reading the documentation. I'll be submitting a pull request to resolve these.

https://www.chisel-lang.org/chisel3/docs/explanations/modules.html

"we can use an active low reset in entire design" -> "in _the_ entire design"

"The clock is just wired as it" -> "The clock is wired as _is_".

https://www.chisel-lang.org/chisel3/docs/explanations/functional-abstraction.html

The equals sign has a closing bracket next to it and the closing parenthesis is within the monospaced block inconsistently.

**Comment by mwachs5** [comment]
thanks for reporting! Looking forward to your PR.
