### ISSUE TITLE
"Naming Cookbook" doc on website is missing a title

### ISSUE THREAD

**Issue by mwachs5** [chipsalliance/chisel3#2157]
**Type of issue**:  documentation 

**Impact**: no functional change 

**Development Phase**: request 

**Other information**
 

This website page: https://www.chisel-lang.org/chisel3/docs/cookbooks/naming.html

is lacking a title. The title should be "Naming Cookbook".
Most of the other pages have such a title (see this page https://www.chisel-lang.org/chisel3/docs/cookbooks/cookbook.html)

**If the current behavior is a bug, please provide the steps to reproduce the problem:**

Look at this page: https://www.chisel-lang.org/chisel3/docs/cookbooks/naming.html
**What is the current behavior?**

There is no title on the actual page, only the sidebar

**What is the expected behavior?**

There should be a title, "Naming Cookbook".

**Please tell us about your environment:**

**What is the use case for changing the behavior?**

Better lookign website.

**Comment by Burnleydev1** [comment]
Hello @mwachs5,  please can I work on this?
