### ISSUE TITLE
GitHub complains our ISSUE_TEMPLATE is out of date

### ISSUE THREAD

**Issue by mwachs5** [chipsalliance/chisel3#2236]
**Type of issue**:  other enhancement

**Impact**: no functional change

**Development Phase**: request

**Other information**
 

**If the current behavior is a bug, please provide the steps to reproduce the problem:**

**What is the current behavior?**

GitHub complains about our current ISSUE_TEMPLATE:
![Screen Shot 2021-11-03 at 2 10 33 PM](https://user-images.githubusercontent.com/17858596/140193331-288f5ac6-052a-4adb-8105-4e5a74405964.png)

**What is the expected behavior?**

GitHub does not complain about our issue template

**Please tell us about your environment:**

**What is the use case for changing the behavior?**

I'm not sure. SOmeone should click that "Learn more" link to see what goodness we could be getting by upgrading our ISSUE_TEMPLATE

**Comment by Burnleydev1** [comment]
Hi @mwachs5, please can I work on this?

**Comment by Burnleydev1** [comment]
I actually think I understand how the new IISUE_TEMPLATE new issue template is created.
should custom Issue template be part of the the options for this project?
![Screenshot from 2021-11-03 23-13-23](https://user-images.githubusercontent.com/81782853/140200657-58010fb5-75af-4524-93a1-273704ced833.png)

**Comment by mwachs5** [comment]
no, we should clean up the bug report / feature request ones and not offer custom issue template to peopel filing issues

**Comment by Burnleydev1** [comment]
Okay @mwachs5 thank you, I think I will need to do the changes from my cloned repo and do a pull request.

**Comment by Burnleydev1** [comment]
Hello @mwachs5, I'm unable to do those changes, probably because it does not work for forked repositories

**Comment by Burnleydev1** [comment]
It works, my browser was glitching.

**Comment by Burnleydev1** [comment]
Hello @mwachs5, I was thinking of adding documentation and other enhancements too, as it is possible to do so.

**Comment by Burnleydev1** [comment]
This is pull request on this issue: https://github.com/chipsalliance/chisel3/pull/2237

**Comment by mwachs5** [comment]
closed by #2237 (and fixed up by #2609 ). Thank you @Burnleydev1 !
