### ISSUE TITLE
CI broken

### ISSUE THREAD

**Issue by schoeberl** [chipsalliance/chisel3#2264]
The following line gives a compilation error at CI tests stopping all open pull requests:

https://github.com/chipsalliance/chisel3/blob/f26f8554879f638b4c4743becbc6da13da174e63/src/main/scala/chisel3/Driver.scala#L54

**Comment by sequencer** [comment]
Yes, sorry for the inconvenience, I’ll be back to office and resolve this before tomorrow. (Hopefully today)

**Comment by jackkoenig** [comment]
This is now fixed.
