### ISSUE TITLE
3.5.0-RC2 breaks all tests from the Chisel book

### ISSUE THREAD

**Issue by schoeberl** [chipsalliance/chisel3#2325]
**Type of issue**: bug report

**If the current behavior is a bug, please provide the steps to reproduce the problem:**

Switch to RC2 in https://github.com/schoeberl/chisel-book.

**What is the current behavior?**

ScalaTest 3.2 changes classes and therefore breaks ScalaTest 3.1 (ChiselTest) code. See https://github.com/ucb-bar/chiseltest/issues/368

**Solution**

Change back to 3.1.4 and provide a warning that this may change in the future.

**Comment by schoeberl** [comment]
Needs probably to be done on all Chisel libraries.

**Comment by ekiwi** [comment]
This is most likely the fault of `iotesters`: https://github.com/ucb-bar/chiseltest/issues/368#issuecomment-1004311026
