### ISSUE TITLE
Isn't .U syntax supposed to only take .W arguments?

### ISSUE THREAD

**Issue by mwachs5** [chipsalliance/chisel3#2413]
**Type of issue**: bug report

**Impact**: API modification

**Development Phase**: request 

**Other information**
 

**If the current behavior is a bug, please provide the steps to reproduce the problem:**

Put this in a `Module`:

```  
val bar = 5
val foo = bar.U(7)
```

Here is a simple Scastie (some commented out code that also all works unexpectedly)
https://scastie.scala-lang.org/nqEQGHEUTziPKNj7NUirBA

**What is the current behavior?**

This code compiles without error

**What is the expected behavior?**

I thought it should be an error to have no `.W` suffix on the arguments inside the `.U`, since those are not supposed to directly take integer arguments

**Please tell us about your environment:**

    - version: 3.5.1
    
**What is the use case for changing the behavior?**

Hard-to-catch unintended user errors

**Comment by jackkoenig** [comment]
This is something we've discussed in the past, I attempted to fix in https://github.com/chipsalliance/chisel3/tree/deprecate-literal-bit-extract and @albert-magyar had a PR proposed to fix via ScalaFix and linting: https://github.com/chipsalliance/chisel3/pull/1449

**Comment by mwachs5** [comment]
>  I attempted to fix in https://github.com/chipsalliance/chisel3/tree/deprecate-literal-bit-extract

What was the issue with the attempt?

**Comment by jackkoenig** [comment]
> What was the issue with the attempt?

I just ran out of steam and was struggling getting all of the cases working. I think we should redo that branch and just do `.U` and `.S`. We also need to make sure those methods don't have parentheses. We can make the suggestion for users who do want to extract immediately to call `.extract` which is a new method we can add that `.apply` is an alias for.
