### ISSUE TITLE
chisel3.internal.ChiselException: operand has escaped the scope of the when in which it was constructed

### ISSUE THREAD

**Issue by IAMAl** [chipsalliance/chisel3#2481]
My code have issue of
"""
[info] - should Test: niconicoProc *** FAILED ***
[info] chisel3.internal.ChiselException: operand has escaped the scope of the when in which it was constructed
[info] at chisel3.internal.throwException$.apply(Error.scala:85)
[info] at chisel3.Data.requireVisible(Data.scala:458)
[info] at chisel3.Data.ref(Data.scala:480)
[info] at chisel3.Element.ref(Element.scala:50)
[info] at chisel3.Bits.binop(Bits.scala:201)
[info] at chisel3.Bool.do_$amp(Bits.scala:1126)
[info] at chisel3.Bool.do_$amp$amp(Bits.scala:1160)
[info] at rob.ROB.$anonfun$new$34(rob.scala:150)
[info] at chisel3.Data.$anonfun$$colon$eq$1(Data.scala:522)
[info] at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
"""
**Code**:
https://github.com/IAMAl/ChiselLivesMatter/tree/main/niconicoProcessor

**sbt version**: sbt 1.5.5 (AdoptOpenJDK Java 11.0.11)

**tester2 version**: "chiseltest" -> "0.3.0+"

**Type of issue**: bug report

**Impact**: API modification

**What is the current behavior?**
 internal exception

**What is the expected behavior?**
no internal exception

**Comment by jackkoenig** [comment]
The main issue is that you are using `Reg` inside of your `Bundle`: https://github.com/IAMAl/ChiselLivesMatter/blob/eae7f85bc69781c7442137c505f59578dbcaabde/niconicoProcessor/src/main/scala/nicoproc/rob/rob.scala#L18

You should not use `Reg` in there, you should use `Reg` on the outside whenever you instantiate a `Bundle`: 

```scala
class Entry extends Bundle {

    val DataWidth   = params.Parameters.DataWidth
    val LogNumReg   = params.Parameters.LogNumReg+1
    
    val V       = Bool()
    val W       = Bool()
    val WBRN    = UInt(LogNumReg.W)
    val Data    = UInt(DataWidth.W)
}
...

// Power of 2 Depth Circular Buffer Memory
val BUFF        = RegInit {
  val initWire = Wire(Vec(BUFFLENGTH, new Entry))
  initWire.foreach { w =>
    w.V := false.B
    w.W := false.B // Also, I suggest not naming signals `W`, `.W` is a built-in function in Chisel so this is pretty ambigous
  }
}

val PostDat     = Reg(new Entry)                     // Output from Memory
```
More info on how to partially initialize registers: https://stackoverflow.com/questions/59049673/how-to-initialize-a-reg-of-bundle-in-chisel/59058082#59058082

Note that on newer versions of Chisel you'll get a better error message here.

I recommend updating first to Chisel 3.4.4 (chiseltest 0.3.4), then to Chisel 3.5.2 (chiseltest 0.5.2) -- you are currently on Chisel 3.4.0 (chiseltest 0.3.0, note that + is not doing anything, you need 0.3.+ if you want it to get the newest minor version).
