### ISSUE TITLE
SyncReadMem: read(addr) problem inside ShiftRegisterMem

### ISSUE THREAD

**Issue by milovanovic** [chipsalliance/chisel3#2879]
**Type of issue**: Bug Report

I believe that the [commit](https://github.com/chipsalliance/chisel3/commit/29665743acff120bc87ee997890d7f952317144e) broke some edge cases of [`ShiftRegisterMem`](https://github.com/ucb-bar/rocket-dsp-utils/blob/master/src/main/scala/craft/ShiftRegisterMem.scala). A detailed demonstration of this bug can be found [here](https://github.com/milovanovic/ShiftRegisterMemDemo).

**Comment by jerryz123** [comment]
I have not looked too closely, but I am inclined to believe that this is actually a bug in the implementation of ShiftRegisterMem. It should not rely on the undefined read-data of a SyncReadMem when the read-enable is low.

**Comment by milovanovic** [comment]
You were right. The problem was indeed inside the `ShiftRegisterMem`. It should be fixed now, so this issue can be closed. Thanks.
