### ISSUE TITLE
[CI] Tabby CAD OSS is Flaky

### ISSUE THREAD

**Issue by seldridge** [chipsalliance/chisel3#2898]
On PRs and `master` commits, the Tabby CAD OSS GitHub action is super flaky. This seems to fail with extremely high probability. 

We should either debug what's going on here or switch to something less flaky.

**Comment by jackkoenig** [comment]
Fixed by https://github.com/chipsalliance/chisel3/pull/2901

**Comment by seldridge** [comment]
Awesome! Thanks, Jack!
