### ISSUE TITLE
Improve PriorityEncoder documentation: output on 0 is undefined

### ISSUE THREAD

**Issue by fanliyong007** [chipsalliance/chisel3#2961]
**Type of issue**: Bug Report

**Please provide the steps to reproduce the problem:**
I use chisel3 to solve the [Problem](https://hdlbits.01xz.net/wiki/Always_case2) a  priority encoder.So I use PriorityEncoder.
The code as shown below.
<code>
class Alwayscase2  extends Module {
  val in=IO(Input(UInt(4.W)))
  val pos=IO(Output(UInt(2.W)))
  val pos_reg=Reg(UInt(2.W))
  pos:=pos_reg
  pos_reg:=PriorityEncoder(in)
}
</code>
It will generate as shown below.I have reduced something inneed
<code>
module top_module(
  input  [3:0] in,
  output  [1:0] pos
);
    always @(*) begin
    if (in[0]) begin // @[Mux.scala 47:70]
      pos <= 2'h0;
    end else if (in[1]) begin // @[Mux.scala 47:70]
      pos <= 2'h1;
    end else if (in[2]) begin // @[Mux.scala 47:70]
      pos <= 2'h2;
    end else begin
      pos <= 2'h3;
    end
  end
endmodule
</code>
but it's wrong when the port 'in' is 4'b000 so I need to change the default  
<code>
module top_module(//this version can solve the problem
  input  [3:0] in,
  output reg [1:0] pos
);
    always @(*) begin
        if (in[0]) begin // @[Mux.scala 47:70]
      pos <= 2'h0;
    end else if (in[1]) begin // @[Mux.scala 47:70]
      pos <= 2'h1;
    end else if (in[2]) begin // @[Mux.scala 47:70]
      pos <= 2'h2;
    end else if (in[3]) begin // @[Mux.scala 47:70]
      pos <= 2'h3;
    end else begin
      pos <= 2'h0;
    end
  end
endmodule
</code>
**What is the current behavior?**
<code>
module Alwayscase2(
  input        clock,
  input        reset,
  input  [3:0] in,
  output reg [1:0] pos
);
`ifdef RANDOMIZE_REG_INIT
  reg [31:0] _RAND_0;
`endif // RANDOMIZE_REG_INIT

  always @(posedge clock) begin
    if (in[0]) begin // @[Mux.scala 47:70]
      pos <= 2'h0;
    end else if (in[1]) begin // @[Mux.scala 47:70]
      pos <= 2'h1;
    end else if (in[2]) begin // @[Mux.scala 47:70]
      pos <= 2'h2;
    end else begin
      pos <= 2'h3;
    end
  end
// Register and memory initialization
`ifdef RANDOMIZE_GARBAGE_ASSIGN
`define RANDOMIZE
`endif
`ifdef RANDOMIZE_INVALID_ASSIGN
`define RANDOMIZE
`endif
`ifdef RANDOMIZE_REG_INIT
`define RANDOMIZE
`endif
`ifdef RANDOMIZE_MEM_INIT
`define RANDOMIZE
`endif
`ifndef RANDOM
`define RANDOM $random
`endif
`ifdef RANDOMIZE_MEM_INIT
  integer initvar;
`endif
`ifndef SYNTHESIS
`ifdef FIRRTL_BEFORE_INITIAL
`FIRRTL_BEFORE_INITIAL
`endif
initial begin
  `ifdef RANDOMIZE
    `ifdef INIT_RANDOM
      `INIT_RANDOM
    `endif
    `ifndef VERILATOR
      `ifdef RANDOMIZE_DELAY
        #`RANDOMIZE_DELAY begin end
      `else
        #0.002 begin end
      `endif
    `endif
`ifdef RANDOMIZE_REG_INIT
  _RAND_0 = {1{`RANDOM}};
  pos_reg = _RAND_0[1:0];
`endif // RANDOMIZE_REG_INIT
  `endif // RANDOMIZE
end // initial
`ifdef FIRRTL_AFTER_INITIAL
`FIRRTL_AFTER_INITIAL
`endif
`endif // SYNTHESIS
endmodule

</code>
**What is the expected behavior?**
<code>
module top_module(//this version can solve the problem
  input  [3:0] in,
  output reg [1:0] pos
);
    always @(*) begin
        if (in[0]) begin // @[Mux.scala 47:70]
      pos <= 2'h0;
    end else if (in[1]) begin // @[Mux.scala 47:70]
      pos <= 2'h1;
    end else if (in[2]) begin // @[Mux.scala 47:70]
      pos <= 2'h2;
    end else if (in[3]) begin // @[Mux.scala 47:70]
      pos <= 2'h3;
    end else begin
      pos <= 2'h0;
    end
  end
endmodule
</code>
**Please tell us about your environment:**
    - version: `3.5-SNAPSHOT`
    - scalaversion:`2.12.13`

**Other Information**

**What is the use case for changing the behavior?**

**Comment by ekiwi** [comment]
The [documentation of the PriorityEncoder](https://www.chisel-lang.org/api/3.2.8/chisel3/util/PriorityEncoder$.html) states:
> Returns the bit position of the least-significant high bit of the input bitvector. 

So if your input is `0` then there is not high bit and thus the output is undefined. Maybe we should add a note to the documentation that says clearly that the input is expected to be one-hot encoded. What do you think?

**Comment by fanliyong007** [comment]
> The [documentation of the PriorityEncoder](https://www.chisel-lang.org/api/3.2.8/chisel3/util/PriorityEncoder$.html) states:
> 
> > Returns the bit position of the least-significant high bit of the input bitvector.
> 
> So if your input is `0` then there is not high bit and thus the output is undefined. Maybe we should add a note to the documentation that says clearly that the input is expected to be one-hot encoded. What do you think?

It's a  good idea.

**Comment by ekiwi** [comment]
Let's keep this open until the documentation is improved.
