### ISSUE TITLE
Incorrect documentation about Bundle.asUInt

### ISSUE THREAD

**Issue by nrother** [chipsalliance/chisel3#2967]
The [documentation of Data.asUInt](https://github.com/chipsalliance/chisel3/blob/master/core/src/main/scala/chisel3/Data.scala#L793) states:

```scala
/*
 * @note Aggregates are recursively packed with the first element appearing
 * in the least-significant bits of the result.
 */
```

The actual behavior is the other way around, the first element is put in the _most_ significant bits. This is also documented [in an Example](https://github.com/chipsalliance/chisel3/blob/master/src/test/scala/cookbook/Bundle2UInt.scala):
```scala
class Bundle2UInt extends CookbookTester(1) {
  // Example
  class MyBundle extends Bundle {
    val foo = UInt(4.W)
    val bar = UInt(4.W)
  }
  val bundle = Wire(new MyBundle)
  bundle.foo := 0xc.U
  bundle.bar := 0x3.U
  val uint = bundle.asUInt
  printf(p"$uint") // 195

  // Test
  assert(uint === 0xc3.U)
}
```
In this code, the first element is `foo`, which value `0xC` followed by `bar` with value `0x3`. The resulting packed UInt is `0xC3`, with the value of `foo` appearing in the MSBs.

**Comment by jackkoenig** [comment]
The documentation is actually correct. What is missing though, is that Bundles store their elements in reverse order from what you might be expecting. `bar` is the "first" element for the Bundle. This should be called out in the documentation for `Bundle` though, I will add it shortly.
