### ISSUE TITLE
Provide API for Casting Bundle to Parent Type for Bulk Connect

### ISSUE THREAD

**Issue by jackkoenig** [chipsalliance/chisel3#582]
I thought there was an issue for this already but I could find it. This is useful when you have some Bundle Type that inherits from another type to add some fields but wants to be bulk connected somewhere as if it is the parent type.

**Comment by mwachs5** [comment]
👍

**Comment by colinschmidt** [comment]
This would be great! The current workarounds I've been using are not very nice...

**Comment by jackkoenig** [comment]
Context for anyone wanting to tackle this issue.

You can fairly easily implement Chisel2-style bulk connect using `Record.elements` (returns `ListMap[String, Data])` and `DataMirror.directionOf` (to get directions).

The tricky part is trying to do something "safer". There's definitely utility in allowing a Bundle to act like a super type (Liskov substitution principle), thus allowing some type of safe casting is an alternative, more complicated solution. I don't know how one might do this non-reflectively, so it could get pretty messy.

**Comment by jackkoenig** [comment]
Fixed in 3.5.0 via DataView (`.viewAsSupertype`)
