### ISSUE TITLE
Review License Practices

### ISSUE THREAD

**Issue by chick** [chipsalliance/chisel3#755]
* **Type of issue**
  - [ ] Bug report
  - [ ] Feature request
  - [x] Other enhancement

* **The following license practices should be reviewed**
  * All repos currently place licenses in src/, github standard is to place these in root.  Should we change this?
  * License files contain dates, should these be updated yearly?
  * First line of chisel-testers license file says Chisel3
  * Any other license issues?

* **Impact**
  - [x] no functional change
  - [ ] API addition (no impact on existing code)
  - [ ] API modification
  - [ ] unknown

* **Development Phase**
  - [x] request
  - [ ] proposal

**Comment by jackkoenig** [comment]
This has been fixed in the switch to Apache 2.0
