### ISSUE TITLE
PeekPokeTester

### ISSUE THREAD

**Issue by schoeberl** [chipsalliance/chisel3#937]
**Type of issue**: bug report

The Chisel 2 tester allowed to peek (and poke?) into the hierarchy of the modules, which was very convenient. Looks like this is gone with the Chisel 3 PeekPokeTester. We need again sire interesting signal up to the top level, which is painful.

**Impact**: issue on porting from Chisel 2 to 3

**Comment by jackkoenig** [comment]
This is now a chiseltest issue although perhaps a "wont fix".
