### ISSUE TITLE
In the process of Chisel to FIRRTL, the ArrayBuffer how to generate FIRRTL after adding Command?

### ISSUE THREAD

**Issue by kai413629305** [chipsalliance/chisel3#972]
For example, object Mux will eventually call the pushCommand function in chiselFrontend/internal/Builder.scala. However, pushCommand calls the addCommand function in UserModule. Scala by adding Command to the variable-length array ArrayBuffer [Command]. How does Array Buffer [Command] generate Mux's FIRRTL?
Detailed pictures are as follows
> https://groups.google.com/forum/#!topic/chisel-users/D4dJv17xN6c

**Comment by jackkoenig** [comment]
Answered in that thread.
