### ISSUE TITLE
Consider Using Scalafix and/or Scalafmt for linting and possibly code rewriting

### ISSUE THREAD

**Issue by jackkoenig** [chipsalliance/chisel3#990]
**Type of issue**: other enhancement

**Impact**: unknown

**Development Phase**: request

**What is the use case for changing the behavior?**

There are three main issues:
1. Style for the Chisel/FIRRTL codebases
1. Style for writing Chisel RTL code
1. Rewriting for code migration (eg. Removing Structural-typed Bundles for Dotty)

[Scalafix](https://scalacenter.github.io/scalafix/) and [Scalafmt](https://scalameta.org/scalafmt/) are modern tools for doing such things.

**Comment by edwardcwang** [comment]
For (2) "Style for writing Chisel RTL code" it would be nice to support/enable organizations with different conventions (e.g. signal names as camelCase vs snake_case)
